name: chatbot
description: Aplicativo de chatbot com autenticação Firebase
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  mask_text_input_formatter: ^2.4.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.19.6
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.5
  intl: ^0.18.1
  image_picker: ^0.8.6
  uuid: ^3.0.7
  string_similarity: ^2.0.0 # Adicionado para correspondência flexível
  flutter_svg: ^2.0.9 # Adicionado para suporte a SVG
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - lib/images/
