// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5NhsWU3MTlsxBfnin_uvXKFQufWHn0Uw',
    appId: '1:678040065414:web:0b0e8036ca63ccabb0c807',
    messagingSenderId: '678040065414',
    projectId: 'chatbot-de18f',
    authDomain: 'chatbot-de18f.firebaseapp.com',
    storageBucket: 'chatbot-de18f.firebasestorage.app',
    measurementId: 'G-B0CVB3YB5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN1yQSGF1p55ZirEWisxvziKSeEmawBWk',
    appId: '1:678040065414:android:49246f8f10261188b0c807',
    messagingSenderId: '678040065414',
    projectId: 'chatbot-de18f',
    storageBucket: 'chatbot-de18f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAHO735PB3AqtYp6tSCm_lmhJ6Wy41lpQ',
    appId: '1:678040065414:ios:50a76193756049a4b0c807',
    messagingSenderId: '678040065414',
    projectId: 'chatbot-de18f',
    storageBucket: 'chatbot-de18f.firebasestorage.app',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAHO735PB3AqtYp6tSCm_lmhJ6Wy41lpQ',
    appId: '1:678040065414:ios:50a76193756049a4b0c807',
    messagingSenderId: '678040065414',
    projectId: 'chatbot-de18f',
    storageBucket: 'chatbot-de18f.firebasestorage.app',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5NhsWU3MTlsxBfnin_uvXKFQufWHn0Uw',
    appId: '1:678040065414:web:5024c53301673dd1b0c807',
    messagingSenderId: '678040065414',
    projectId: 'chatbot-de18f',
    authDomain: 'chatbot-de18f.firebaseapp.com',
    storageBucket: 'chatbot-de18f.firebasestorage.app',
    measurementId: 'G-DQLX57YJNB',
  );
}